### ISSUE TITLE
fileuri is not accessible on the device. It works fine on the emulator.

### ISSUE THREAD

**Issue by girishgkg** [NativeScript/sample-ImageUpload#1]
CONSOLE LOG file:///app/main-page.js:81:15: TypeError: undefined is not an object (evaluating 'fileUri.match')

**Comment by NickIliev** [comment]
related to [#13](https://github.com/NativeScript/nativescript-imagepicker/issues/13)

**Comment by dtopuzov** [comment]
Will be solved once https://github.com/NativeScript/nativescript-imagepicker/issues/13 is fixed.
