### ISSUE TITLE
Angular ImageUpload and API level >= 26

### ISSUE THREAD

**Issue by js26** [NativeScript/sample-ImageUpload#20]
It seems like it's not possible to make the same in an Angular version and run it on an Android Emulator with a higher API level than 25. Oreo doesn't work. But Android 7.1.1 (Nougat) does.

If I add the parameter  androidDisplayNotificationProgress : false to the request object, I get : Android Oreo requires a notification configuration for the service to run
And if I don't add this parameter, I get a little popup in the emulator with the text: Failed to post notification on channel "null"
Are there any help out there ? 
You can see my angular version here 
https://drive.google.com/file/d/1RxPA9B3q3vRUlL2PKr61WehrIgNlp6JD/view?usp=sharing

**Comment by fthuin** [comment]
You should take a look here https://github.com/NativeScript/nativescript-background-http/issues/124

**Comment by tsonevn** [comment]
Hi @js26,
Can you check if you will be able to recreate the issue with the latest version of the `nativescript-background-http` `3.3.0`?
