### ISSUE TITLE
Error: net is not defined occuring with uploading image using Nativescript-background-http

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/sample-ImageUpload#4]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function

ReferenceError: net is not defined
File: ", line: 1, column: 265

StackTrace: 
Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/tns_modules/nativescript-background-http/background-http.js', line: 9, column: 22
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/pages/login/image-upload.js', line: 13, column: 14
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/app.routes.js', line: 3, column: 22
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.groceries/files/app/main.js', line: 6, column: 20
Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplica

**Comment by JaganJonnala** [comment]
My code base is with Nativescript-Angular (TypeScript)

**Comment by tsonevn** [comment]
related to issue [#27](https://github.com/NativeScript/nativescript-background-http/issues/27)
