### ISSUE TITLE
Could not resolve net.gotev:uploadservice:3.0.3.

### ISSUE THREAD

**Issue by alexgv99** [NativeScript/sample-ImageUpload#8]
Application chashes on start...

**Comment by tsonevn** [comment]
Hi @alexgv99,
Could you provide some more info about the problem?

I reviewed your case, however, was unable to reproduce it on my side. It would help if you gives us info about your environment (`CLI`, `tns-core-modules`) and the device or emulator, which you are using for testing. 
You could also build the project with `tns run <platform name> --log trace` and to send us the log from console.
